version: '2'
services:
  awestruct:
    build: ../../awestruct
    command:
      - "rake git_setup clean gen[drupal_pull_request]"
    links:
      - drupal
      - searchisko
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
      - ../../awestruct/overlay/ssh-key:/home/awestruct/.ssh
    environment:
      - google_api_key
      - dcp_user
      - dcp_password
      - vimeo_client_secret
      - vimeo_access_token_secret
      - vimeo_access_token
      - cache_password
      - cache_url
      - site_base_path
      - site_path_suffix
      - cdn_prefix
      - cache_user
      - github_token
      - drupal_user
      - drupal_password
      - ACCESSIBLE_SLAVE_IP
      - SEARCHISKO_HOST_PORT
      - DRUPAL_HOST_PORT
      - DRUPAL_HOST_IP
      - ghprbActualCommit
      - github_status_api_token
      - BUILD_URL
      - AWE_PROC_COUNT=10

  drupal:
    build: ../../drupal
    ports:
      - "80"
    links:
      - drupalmysql
      - searchisko
    volumes:
      - ../../drupal:/var/www/drupal
      - ../../../images:/var/www/html/images:ro
      - ../../../stylesheets/fonts:/var/www/html/fonts:ro

  drupalmysql:
    image: mariadb:10.0.15
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=drupal
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"

  mysql:
    build: ../../mysql
    volumes:
      - ../../mysql:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=searchisko
      - MYSQL_USER=searchisko
      - MYSQL_PASSWORD=searchisko
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"

  searchisko:
    build: ../../searchisko
    expose:
     - "8080"
    ports:
     - "8080"
    environment:
      - DB_NAME=searchisko
      - DB_USER=searchisko
      - DB_PASSWORD=searchisko
    links:
     - mysql

  #
  # Environment actions
  #
  export:
     user: root
     build: ../../awestruct
     volumes:
      - ../../../:/home/awestruct/developer.redhat.com
      - ../../awestruct/overlay/ssh-key:/home/awestruct/.ssh
      - export:/export
     entrypoint: "ruby _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb 'ruby _docker/lib/export/export.rb stumpjumper.lab4.eng.bos.redhat.com:${DRUPAL_HOST_PORT}'"
     environment:
      - github_status_api_token
      - github_status_context=Drupal:Site Preview
      - github_status_repo=robpblake/developers.redhat.com
      - github_status_target_url=${site_base_path}:${site_path_suffix}
      - github_status_sha1=${ghprbActualCommit}

  #
  # Testing
  #
  unit_tests:
   build: ../../awestruct
   volumes:
    - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "ruby _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb 'bundle exec rake test'"
   environment:
    - github_status_api_token
    - github_status_context=Drupal:Unit Tests
    - github_status_repo=robpblake/developers.redhat.com
    - github_status_target_url=${BUILD_URL}
    - github_status_sha1=${ghprbActualCommit}
    - github_status_initialise=Drupal:Unit Tests,Drupal:Acceptance Tests,Drupal:Site Preview,Drupal:Blinkr

  acceptance_tests:
   build: ../../awestruct
   volumes:
     - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "ruby _docker/lib/pull_request/exec_with_git_hub_status_wrapper.rb"
   environment:
     - github_status_api_token
     - github_status_context=Drupal:Acceptance Tests
     - github_status_repo=robpblake/developers.redhat.com
     - github_status_target_url=${BUILD_URL}
     - github_status_sha1=${ghprbActualCommit}
     - PARALLEL_TEST
     - CUCUMBER_TAGS
     - SELENIUM_HOST=http://selhub:4444/wd/hub
     - RHD_JS_DRIVER
     - RHD_DOCKER_DRIVER

#
# Volumes
#
volumes:
 export:
  driver: local