---
version: '3'
services:

  seed_env:
    build:
      context: ../rhdp-data-seed
    environment:
    - DEPLOYMENT_ID=1
    volumes:
    - ./drupal-workspace:/drupal-workspace
    - backups:/drupal-backups

  bootstrap_env:
    build:
      context: ../../../../Dockerfile.mp
    entrypoint: ["/bin/bash", "-c", "ansible-playbook bootstrap-env.yml"]
    working_dir: "/ansible"
    environment:
    - DEPLOYMENT_ID=1
    volumes:
    - ../../:/ansible
    - ../env.yml:/credentials/ansible/env.yml
    - ./drupal-workspace:/drupal-workspace
    - backups:/drupal-backups
    depends_on:
    - mysql

  backup_drupal:
    build:
      context: ../../../
    entrypoint: ["/bin/bash"]
    working_dir: "/ansible"
    user: root
    environment:
      - DEPLOYMENT_ID=1
    volumes:
    - ../../:/ansible
    - ../env.yml:/credentials/ansible/env.yml
    - ./drupal-workspace/drupal_1/drupal/credentials/rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
    - ./drupal-workspace/drupal_1/drupal/credentials/rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
    - ./drupal-workspace/drupal_1/drupal/files:/var/www/drupal/web/sites/default/files
    - ./drupal-workspace/drupal_1/drupal/config/active:/var/www/drupal/web/config/active
    - backups:/drupal-backups
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.3.9-bionic
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=drupal_1
    expose:
      - 3306
volumes:
  backups:
    driver: local