properties([
    disableConcurrentBuilds(),
    [$class: 'HudsonNotificationProperty', enabled: false],
    [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false],
    [$class: 'ParametersDefinitionProperty', parameterDefinitions: [[$class: 'hudson.model.StringParameterDefinition', defaultValue: '', description: 'The Drupal Docker image used to build the data images.', name: 'DRUPAL_IMAGE']]],
    [$class: 'ThrottleJobProperty', categories: [], limitOneJobWithMatchingParams: false, maxConcurrentPerNode: 0, maxConcurrentTotal: 0, paramsToUseForLimit: '', throttleEnabled: false, throttleOption: 'project']
])

def failure

node('cic-rhd-01') {
    try {
        timeout(30) {
            stage('Checkout SCM') {
                echo "Starting the build for build number '${BUILD_NUMBER}'..."
                checkout scm
            }
        }
    } catch(e) {
        failure = e
        currentBuild.result == 'FAILURE'
    } finally {
        stage('Clean up') {
            sh 'ls /tmp'
        }
    }
}