properties([
    disableConcurrentBuilds(),
    [$class: 'HudsonNotificationProperty', enabled: false],
    [$class: 'RebuildSettings', autoRebuild: false, rebuildDisabled: false],
    [$class: 'ParametersDefinitionProperty', parameterDefinitions: [[$class: 'hudson.model.StringParameterDefinition', defaultValue: '', description: 'The SHA256 of the Drupal Docker image used to build the data images.', name: 'DRUPAL_IMAGE_SHA256']]],
    [$class: 'ThrottleJobProperty', categories: [], limitOneJobWithMatchingParams: false, maxConcurrentPerNode: 0, maxConcurrentTotal: 0, paramsToUseForLimit: '', throttleEnabled: false, throttleOption: 'project']
])

def failure

node('cic-rhd-01') {
    try {
        timeout(30) {

            dir('_docker/drupal/data-image') {
                stage('Checkout SCM') {
                    echo "Starting the build for build number '${BUILD_NUMBER}'..."
                    checkout scm
                }

                stage('Pull the Drupal Docker Image') {
                    sh "docker pull registry.paas.redhat.com/rhdp/developer-drupal@sha256${params.DRUPAL_IMAGE_SHA256}"
                }
            }
        }
    } catch(e) {
        failure = e
        currentBuild.result == 'FAILURE'
    } finally {
        stage('Clean up') {
            sh 'ls /tmp'
        }

        if(failure != null) {
            throw failure
        }

    }
}