version: '2'
services:
  update-composer:
    image: registry.paas.redhat.com/rhdp/rhdp-base
    working_dir: /drupal
    volumes:
      - ../../drupal/drupal-filesystem/composer.json:/drupal/composer.json
      - ../../drupal/drupal-filesystem/composer.lock:/drupal/composer.lock
      - ../../drupal/drupal-filesystem/scripts/ScriptHandler.php:/drupal/scripts/ScriptHandler.php

  drupal:
    build:
      context: ../../drupal
      args:
        composer_profile: development
    ports:
      - "80:8080"
      - "443:8443"
    expose:
      - 8443
    environment:
      - FORTAWESOME_REGISTRY
    links:
    # We give the drupalmysql the 'docker' alias so that the rhd.settings.php for database host name
    # work both within the container and also when running Drupal outside of Docker
      - drupalmysql:docker
    volumes:
      - ./rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
      - ./rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
      - ./ssl/developers.dev.redhat.com.crt:/ssl/drupal.crt
      - ./ssl/developers.dev.redhat.com.key:/ssl/drupal.key
      - ./env.yml:/credentials/ansible/env.yml
      - ../../drupal/drupal-filesystem/web/themes/custom:/var/www/drupal/web/themes/custom
      - ../../drupal/drupal-filesystem/web/modules/custom:/var/www/drupal/web/modules/custom
      - ../../drupal/drupal-filesystem/web/config/sync:/var/www/drupal/web/config/sync
      - ./drupal-logs:/var/log/httpd
      - /tmp/drupal-workspace:/drupal-workspace
      - ../../drupal/ansible:/ansible
    volumes_from:
      - drupal_data

  drupalmysql:
    image: mariadb:10.0.24
    environment:
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
      - MYSQL_DATABASE=rhd_mysql
      - MYSQL_ROOT_PASSWORD=superdupersecret
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/my.cnf:/etc/mysql/my.cnf
    volumes_from:
      - drupal_data

  apache:
   image: httpd:2.4.20
   command: "sh -c 'rm -f /usr/local/apache2/htdocs/index.html && httpd-foreground'"
   links:
    - drupal:docker
   expose:
    - 80
    - 9000
   ports:
    - "9000:9000"
   volumes:
    - export:/usr/local/apache2/htdocs
    - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    - ./apache/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf

  # Drupal production data
  drupal_data:
   image: redhatdeveloper/drupal-data-lite:latest
   volumes:
    - /var/www/drupal/web/config/active
    - /var/www/drupal/web/sites/default/files
    - /docker-entrypoint-initdb.d

  #
  # Environment actions
  #
  export:
    links:
     - drupal:docker
    build: ../../export
    volumes:
     - ../../../:/home/jenkins_developer/developer.redhat.com
     - ../../../images:/home/jenkins_developer/developer.redhat.com/_docker/lib/export/static/images:ro
     - export:/export
    entrypoint: "ruby _docker/lib/export/export.rb docker"
    environment:
     - drupal.export.fail_on_missing
     - drupal.export.final_base_url=http://docker:9000/

  #
  # Testing
  #
  unit_tests:
   build: ../../awestruct
   volumes:
    - ../../../:/home/awestruct/developer.redhat.com
   entrypoint: "bundle exec rake test"

#
# Volumes
#
volumes:
 drupal-workspace:
  driver: local
 export:
  driver: local
