---
- hosts: localhost
  connection: local
  become: no
  vars_files:
    - "/credentials/ansible/env.yml"
    - "vars/common/drupal/vars.yml"
  tasks:
    - name: Generate timestamp for run of backup
      set_fact:
        backup_name: "{{ drupal_deployment_dir }}-{{ '%Y-%m-%d-%H-%M-%S' | strftime(ansible_date_time.epoch) }}"

    - name: Create backup directory name
      set_fact:
        backup_dir: "/tmp/{{ backup_name }}"

    - debug:
        msg: "The backup directory will be '{{ backup_dir }}'"

    - name: Create the directory to store backup artifacts
      file:
        path: '{{ backup_dir }}'
        group: 'root'
        state: directory
        recurse: yes
        mode: 0770

    - name: Record the name of backup
      copy:
        content: "{{ backup_name }}"
        dest: "{{ backup_dir }}/current.backup"
        force: no
        group: 'root'
        mode: '0770'

    - name: Perform a backup of the Drupal database using Drush
      shell: "drush sql:dump --gzip --result-file='{{ backup_dir }}/drupal-db.sql'"
      args:
        chdir: '/var/www/drupal'

    - name: Perform a backup of the Drupal filesystem using tar
      shell: "tar -cvzf {{ backup_dir }}/drupal-filesystem.tar.gz -C /var/www/drupal/web config/active sites/default/files"

    - name: Upload database backup to S3
      aws_s3:
        bucket: "{{ drupal_s3_bucket }}"
        object: "{{ backup_name}}/drupal-db.sql.gz"
        src: "{{ backup_dir }}/drupal-db.sql.gz"
        mode: put
        region: eu-west-1
        aws_access_key: '{{ drupal_s3_access_key }}'
        aws_secret_key: '{{ drupal_s3_secret_key }}'

    - name: Upload filesystem backup to S3
      aws_s3:
        bucket: "{{ drupal_s3_bucket }}"
        object: "{{ backup_name}}/drupal-filesystem.tar.gz"
        src: "{{ backup_dir }}/drupal-filesystem.tar.gz"
        mode: put
        region: eu-west-1
        aws_access_key: '{{ drupal_s3_access_key }}'
        aws_secret_key: '{{ drupal_s3_secret_key }}'

    - name: Record the latest backup in S3
      aws_s3:
        bucket: "{{ drupal_s3_bucket }}"
        object: "current.backup"
        src: "{{ backup_dir }}/current.backup"
        mode: put
        region: eu-west-1
        aws_access_key: '{{ drupal_s3_access_key }}'
        aws_secret_key: '{{ drupal_s3_secret_key }}'

    - name: Cleanup backup directory
      file:
        path: '{{ backup_dir }}'
        state: absent