environment: dev
broker: https://broker.staging.redhat.com/partner/drc/userMapping?redirect=
downloadManager:
  baseUrl: 'https://developers.stage.redhat.com'
  fileBaseUrl: '//developers.stage.redhat.com/download-manager/file/'
keycloak:
  accountUrl: 'https://developers.stage.redhat.com/auth/'
  authUrl: 'https://developers.stage.redhat.com/auth/'
drupal:
  host: docker
  port: "80"
searchisko:
  host: docker
  protocol: "http"
  port: "8080"
  baseProtocolRelativeUrl: 'docker:8080'
database:
  host:  drupalmysql
  port: '3306'
  username: 'drupal'
  password: 'drupal'
  name: 'rhd_mysql'
