version: '2'
services:
  drupal:
    build:
     context: ../../drupal
     args:
       http_proxy: proxy01.util.phx2.redhat.com:8080
       https_proxy: proxy01.util.phx2.redhat.com:8080
       composer_profile: production
    ports:
      - "80:80"
    restart: 'unless-stopped'
    volumes:
      - /credentials/drupal/rhd.settings.yml:/var/www/drupal/web/sites/default/rhd.settings.yml
      - /credentials/drupal/rhd.settings.php:/var/www/drupal/web/sites/default/rhd.settings.php
      - /data/drupal/files:/var/www/drupal/web/sites/default/files
      - /data/drupal/config/lightning:/var/www/drupal/web/config/active
      - /data/drupal-logs/lightning:/var/log/httpd
      - /data/drupal/npm-cache:/root/.npm
    environment:
      - http_proxy=proxy01.util.phx2.redhat.com:8080
      - https_proxy=proxy01.util.phx2.redhat.com:8080
      - FORTAWESOME_REGISTRY


  #
  # Environment actions
  #
  backup:
    build:
     context: ../../backup
     args:
       http_proxy: proxy01.util.phx2.redhat.com:8080
       https_proxy: proxy01.util.phx2.redhat.com:8080
    entrypoint: ruby developer.redhat.com/_docker/lib/backup/backup.rb
    environment:
      - http_proxy=proxy01.util.phx2.redhat.com:8080
      - https_proxy=proxy01.util.phx2.redhat.com:8080
    volumes:
      - ../../../:/home/jenkins_developer/developer.redhat.com
      - /data/drupal:/drupal
      - /data/git/backups:/backups
      - /credentials/db/my.cnf:/home/jenkins_developer/.my.cnf
      - /credentials/git/backups/netrc:/home/jenkins_developer/.netrc

  export:
    build:
     context: ../../export
     args:
       http_proxy: proxy01.util.phx2.redhat.com:8080
       https_proxy: proxy01.util.phx2.redhat.com:8080
    entrypoint: "ruby _docker/lib/export/export.rb rhdp-drupal.redhat.com"
    volumes:
      - /data/drupal-export:/export
      - /credentials/rsync:/home/jenkins_developer/.ssh
      - /credentials/akamai/edgerc:/home/jenkins_developer/.edgerc
      - ../../../:/home/jenkins_developer/developer.redhat.com
    environment:
     - drupal.export.fail_on_missing
     - drupal.export.attempt_invalidate_cache

  rollback:
    build:
     context: ../../export
     args:
      http_proxy: proxy01.util.phx2.redhat.com:8080
      https_proxy: proxy01.util.phx2.redhat.com:8080
    entrypoint: "ruby _docker/lib/rollback/rollback.rb rhd@filemgmt.jboss.org:/www_htdocs/it-rhd-drupal"
    volumes:
     - /data/drupal-export:/export
     - /credentials/rsync:/home/jenkins_developer/.ssh
     - ../../../:/home/jenkins_developer/developer.redhat.com

  #
  # Testing
  #
  unit_tests:
    build:
      context: ../../awestruct
      args:
        http_proxy: proxy01.util.phx2.redhat.com:8080
        https_proxy: proxy01.util.phx2.redhat.com:8080
    volumes:
      - ../../../:/home/awestruct/developer.redhat.com
    entrypoint: "bundle exec rake test"
