---
apiVersion: v1
kind: Template
metadata:
  name: drupal-statefulset
  annotations:
    openshift.io/display-name: "Template for the StatefulSet deployment of Drupal."
    description: "A StatefulSet that deploys a specific image of Drupal"
    iconClass: icon-drupal
labels:
  drupal-deployment-id: "${DEPLOYMENT_ID}"
parameters:
- name: DEPLOYMENT_ID
  description: "The id of Drupal deployment that we are creating."
  required: true
- name: IMAGE_REPOSITORY
  description: "The Image Repository to pull Docker Images from"
  required: true
  value: "registry.paas.redhat.com/rhdp/"
- name: DRUPAL_DATA_IMAGE_REPOSITORY
  description: "The Image Repository to pull the Drupal Data Image from"
  required: true
  value: "docker-registry.default.svc:5000/rhdp--prototype/"
objects:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    name: drupal-deployment-${DEPLOYMENT_ID}
  spec:
    serviceName: "drupal-headless-${DEPLOYMENT_ID}"
    replicas: 3
    activeDeadlineSeconds: "1200"
    selector:
      matchLabels:
        drupal-deployment-id: "${DEPLOYMENT_ID}"
    template:
      metadata:
        labels:
          drupal-deployment-id: "${DEPLOYMENT_ID}"
      spec:
        initContainers:
        - name: rhdp-data-seed
          image: ${DRUPAL_DATA_IMAGE_REPOSITORY}drupal-data-lite:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          command:
            - sh
            - "-c"
            - |
              if [ ! -d "/drupal-workspace/drupal_$DEPLOYMENT_ID/drupal/config/active" ]
              then
                  BACKUP_DATE=`date -u '+%Y-%m-%d-%H-%M-%S'`
                  BACKUP_DIR="/drupal-backups/drupal_$DEPLOYMENT_ID-$BACKUP_DATE"
                  mkdir -p "$BACKUP_DIR"
                  cp "/docker-entrypoint-initdb.d/drupal-db.sql.gz" "$BACKUP_DIR/drupal-db.sql.gz"
                  cd /var/www/drupal/web
                  tar czf "$BACKUP_DIR/drupal-filesystem.tar.gz" config sites
                  chgrp -R root "$BACKUP_DIR"
                  chmod -R 775 "$BACKUP_DIR"
              else
                  echo "Seed of environment has already been completed"
              fi
          env:
          - name: DEPLOYMENT_ID
            value: '${DEPLOYMENT_ID}'
          volumeMounts:
          - name: drupal-workspace
            mountPath: /drupal-workspace
          - name: drupal-backups
            mountPath: /drupal-backups
        - name: rhdp-bootstrap-env
          image: ${IMAGE_REPOSITORY}rhdp-drupal
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          env:
          - name: DEPLOYMENT_ID
            value: '${DEPLOYMENT_ID}'
          args: ['/usr/bin/ansible-playbook', '/ansible/bootstrap-env.yml']
          volumeMounts:
          - name: drupal-workspace
            mountPath: /drupal-workspace
          - name: environment-secrets
            mountPath: /credentials/ansible
        - name: rhdp-bootstrap-drupal
          image: ${IMAGE_REPOSITORY}rhdp-drupal
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi
          env:
          - name: DEPLOYMENT_ID
            value: '${DEPLOYMENT_ID}'
          args: ['/usr/bin/ansible-playbook','/ansible/bootstrap-drupal.yml']
          volumeMounts:
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/sites/default/rhd.settings.yml
            subPath: drupal_${DEPLOYMENT_ID}/drupal/credentials/rhd.settings.yml
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/sites/default/rhd.settings.php
            subPath: drupal_${DEPLOYMENT_ID}/drupal/credentials/rhd.settings.php
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/sites/default/files
            subPath: drupal_${DEPLOYMENT_ID}/drupal/files
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/config/active
            subPath: drupal_${DEPLOYMENT_ID}/drupal/config/active
          - name: drupal-workspace
            mountPath: /drupal-workspace
          - name: environment-secrets
            mountPath: /credentials/ansible
        containers:
        - name: "drupal"
          image: ${IMAGE_REPOSITORY}rhdp-drupal
          imagePullPolicy: Always
          command: ['/uid_entrypoint.sh']
          args: ['/var/www/drupal/run-httpd.sh']
          resources:
            requests:
              cpu: 1
              memory: 2Gi
            limits:
              cpu: 1
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 20
            httpGet:
              path: /
              port: 8080
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 20
            httpGet:
              path: /
              port: 8080
          ports:
          - containerPort: 8080
            name: http
            protocol: "TCP"
          - containerPort: 8443
            name: https
            protocol: "TCP"
          volumeMounts:
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/images
            subPath: drupal_${DEPLOYMENT_ID}/developers.redhat.com/images
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/sites/default/rhd.settings.yml
            subPath: drupal_${DEPLOYMENT_ID}/drupal/credentials/rhd.settings.yml
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/sites/default/rhd.settings.php
            subPath: drupal_${DEPLOYMENT_ID}/drupal/credentials/rhd.settings.php
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/sites/default/files
            subPath: drupal_${DEPLOYMENT_ID}/drupal/files
          - name: drupal-workspace
            mountPath: /var/www/drupal/web/config/active
            subPath: drupal_${DEPLOYMENT_ID}/drupal/config/active
          - name: drupal-ssl
            mountPath: /ssl
          - name: drupal-backups
            mountPath: /drupal-backups
          - name: environment-secrets
            mountPath: /credentials/ansible
        volumes:
        - name: drupal-workspace
          persistentVolumeClaim:
            claimName: drupal-workspace
        - name: drupal-backups
          persistentVolumeClaim:
            claimName: drupal-backups
        - name: environment-secrets
          secret:
            secretName: environment-secrets
            optional: false
        - name: drupal-ssl
          secret:
            secretName: drupal-ssl
            optional: false